Merge Sort
ayan-biswas0412/AlgoDocs pull request #26
Opened 2021-10-03 16:41 UTC by Ronak55

Implemented merge sort algorithm in both cpp and python

2021-10-03 18:41 UTC, ayan-biswas0412 commented
> Implemented merge sort algorithm in both cpp and python

I think you have done Javascript and cpp right ?

2021-10-03 18:42 UTC, ayan-biswas0412 requested changes
Please add proper heading for each of the languages you have implemented

2021-10-03 21:14 UTC, Ronak55 reviewed
My bad, i just wrote python by mistake i did it on js and cpp

2021-10-04 17:56 UTC, ayan-biswas0412 commented on docs/sorting/merge_sort.md
> +
```suggestion
### JavaScript Implementation
```

2021-10-04 17:57 UTC, merged